FROM node:14-alpine as builder

ARG HTTP_PORT=8002
ARG GRPC_PORT=8012

RUN apk add --no-cache make gcc g++ python3

WORKDIR /usr/src/app

RUN chown node:node /usr/src/app

USER node

COPY ./package*.json ./
RUN npm install

COPY --chown=node:node ./ /usr/src/app
RUN mv /usr/src/app/config/.env.production.02 /usr/src/app/config/.env.production && cp /usr/src/app/config/.env.production /usr/src/app/config/.env
RUN cat /usr/src/app/config/.env && npm run prod

FROM node:14-alpine as runtime

WORKDIR /usr/src/app

RUN chown node:node /usr/src/app
RUN mkdir -p /usr/src/data
RUN chown node:node /usr/src/data

COPY --chown=node:node --from=builder /usr/src/app/builds/prod /usr/src/app/builds/prod 

USER node
RUN cd /usr/src/app/builds/prod && npm install --only=prod

USER root

EXPOSE ${HTTP_PORT}
EXPOSE ${GRPC_PORT}

CMD ["sh", "-c", "node ./builds/prod/src/backend/db/cli/ExecuteMigrations.js&& node ./builds/prod/src/ServerCluster.js"]