FROM node:14-alpine

RUN apk add --no-cache make gcc g++ python

WORKDIR /usr/src/app

RUN chown node:node /usr/src/app
RUN mkdir -p /usr/src/data
RUN chown node:node /usr/src/data

USER node

COPY ./package*.json ./

RUN npm install

USER root

COPY --chown=node:node ./ ./

CMD ["sh", "-c", "npm run dev-migrate-db-01&& npm run dev-01"]